
```{r setup, include = FALSE} 
knitr::opts_chunk$set(warning = FALSE, message = FALSE) 
library(leaflet)
```

# Interactive Plots

## Plot 1 (numeric)

```{r}
nursing_summary <- nursing_summary |>
  mutate(num_labs_1 = str_c(name, ": ", snf_mean_stay_round, " days"))
pal <- colorNumeric("Blues", nursing_summary$snf_mean_stay_round)


leaflet(nursing_summary) |>
  addTiles() |> 
  setView(lng = -96.25,
          lat = 40,
          zoom = 3.5) |>
  addPolygons(weight = 2,
              opacity = 1,
              color = "black",
              fillColor = ~ pal(nursing_summary$snf_mean_stay_round),
              fillOpacity = 0.7,
              label = ~ num_labs_1,
              highlightOptions = highlightOptions(weight = 4,
                                                  color = "#668",
                                                  fillOpacity = 0.8,
                                                  bringToFront = TRUE),
              labelOptions = labelOptions(style = list("font-weight" = "normal",
                                                       padding = "3px 8px"),
                                          textsize = "15px",
                                          direction = "auto")) |>
  addLegend(pal = pal,
            values = ~ nursing_summary$snf_mean_stay_round,
            title = paste("Average SNF<br>Stay Length"),
            position = "bottomright")
              
```

## Plot 2 (categorical)

**Note: there are no observations in the \$20 million - \$25 million category so I did not provide a color for that level.**

```{r}
nursing_summary <- nursing_summary |>
mutate(cat_labs_1 = paste0("Total Gross Revenue: ", tot_gross_revenue, "<br>",
                         "Number of Nursing Homes: ", homes_per_state, "<br>",
                         "Average Gross Revenue Per Home: ", tot_revenue_homes_round))
        
labels <- lapply(nursing_summary$cat_labs_1, HTML)

levels(nursing_summary$revenue_cat)
factpal <- colorFactor(c("#8FDA04FF",
                         "#009F3FFF",
                         "#132157FF",
                         "#FFF800FF"),
                       levels(nursing_summary$revenue_cat))


leaflet(nursing_summary) |>
  setView(lng = -96.25,
          lat = 40,
          zoom = 3.5) |>
  addTiles() |> 
  addPolygons(weight = 2,
              opacity = 1,
              color = "black",
              fillColor = ~ factpal(nursing_summary$revenue_cat),
              dashArray = "1",
              fillOpacity = 0.7,
  highlightOptions = highlightOptions(weight = 5,
                                      color = "#666",
                                      fillOpacity = 0.7,
                                      bringToFront = TRUE),
  label = labels,
  labelOptions = labelOptions(style = list("font-weight" = "normal",
                                           padding = "3px 8px"),
                              textsize = "15px",
                              direction = "auto")) |>
  addLegend(pal = factpal,
            values = ~ nursing_summary$revenue_cat, 
            opacity = 0.7,
            title = "Gross Revenue",
            position = "bottomright")

```

*TWIN FOUNTAINS HOME of GA had a gross revenue of \$1,300,406,865 and was removed for this analysis.*
