project:
  type: website
  output-dir: docs

website:
  title: "Elise Hachfeld"
  site-url: https://elisefeld.github.io/
  navbar:
    left:
      - href: index.qmd
        text: home
      - about.qmd
      - href: projects.qmd
      - text: projects
  page-footer: 
    background: light
    left: © 2024 Elise Hachfeld

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

